name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Target platform and compiler set'
        required: true
        default: 'x64-intel'
        type: choice
        options:
          - x64-intel
          - x64-amd
          - arm64-acfl
      pull:
        description: 'Pull base images'
        required: true
        default: true
        type: boolean
      push:
        description: 'Push images'
        required: true
        default: true
        type: boolean
  schedule:
    - cron: '0 1 * * *'

jobs:
  setup:
    runs-on: ubuntu-24.04
    outputs:
      runner: ${{ steps.step1.outputs.runner }}
    steps:
      - name: Check target architecture
        id: step1
        run: |
          if [ ${{ inputs.platform }} == 'arm64-acfl' ]; then
            echo "runner=ubuntu-24.04-arm" >> $GITHUB_OUTPUT
          else
            echo "runner=ubuntu-24.04" >> $GITHUB_OUTPUT
          fi
  
  build:
    needs: [setup]
    runs-on: ${{ needs.setup.outputs.runner }}

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/bake-action@v6
      working-directory: ./docker/ol8
      with:
        files: ./docker/ol8/docker-bake.hcl
        push: ${{ inputs.push }}
        pull: ${{ inputs.pull }}
        targets: ${{ inputs.platform }}
